### ISSUE TITLE
Adding link

### ISSUE THREAD

**Issue by Counteruse** [sunwaytechclub/hacktoberfest-2019#10]
Add link for the participle to sign up and download the necessary account and software.
1. github.com
2. hacktoberfest.digitalocean.com
3. Git Hub Desktop (https://desktop.github.com/)
4. Text editor (https://www.sublimetext.com/)

**Comment by VenatusSimpleX** [comment]
This feat can be done via editing the `index.md` file if you want to do it yourself.

Otherwise it’ll be done later as I’m not free at the moment.

Also, remember to assign yourself if you want to do this, so multiple people won't be doing the same thing at the same time.

**Comment by VenatusSimpleX** [comment]
Also, remember to assign yourself if you want to do this, so others won’t do it you multiple people doing the same thing at the same time
